version: "3"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: DATABASE_NAME
      POSTGRES_USER: DATABASE_USER
      POSTGRES_PASSWORD: DATABASE_PASSWORD
    ports:
      - "5432:5432"
  django:
    build: .
    volumes:
      - media_storage:/usr/local/app/media
      - private_storage:/usr/local/app/private
      - ./logs:/var/log
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: {{cookiecutter.project_name}}
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DJANGO_SETTINGS_MODULE: {{cookiecutter.project_name}}.settings.development
      REDIS_HOST: redis
      SECRET_KEY: 'oqjwvmob^(qwlil^8ub8%a@o5@a!^x0j1*^*1m@y46k%(6+w'
    ports:
      - 8000:8000
    depends_on:
      - db
  redis:
    image: "redis:6-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    environment:
      REDIS_REPLICATION_MODE: master
volumes:
  private_storage:
  media_storage:
