openapi: 3.0.0
info:
  title: {{cookiecutter.project_name}} API
  description: OpenAPI definition to documentation for the {{cookiecutter.project_name}} API.
  version: 0.1.0

servers:
  - url: http://127.0.0.1:8000/api/v1
    description: Localhost development server
  - url: https://api.dev.{{cookiecutter.project_name}}.sk/api/v1
    description: Staging server
  - url: https://api.{{cookiecutter.project_name}}.sk/api/v1
    description: Production server

paths:
  /token:
    $ref: "views/token.yaml#/TokenManagement"

  /users:
    $ref: "views/user.yaml#/UserManagement"
  /users/me:
    $ref: "views/user.yaml#/UserMe"
  /users/{user_id}:
    $ref: "views/user.yaml#/UserDetail"
  /users/{user_id}/password:
    $ref: "views/user.yaml#/ChangePasswordDetail"

  /password/recovery:
    $ref: "views/password.yaml#/PasswordRecoveryManagement"
  /password/change:
    $ref: "views/password.yaml#/ChangePasswordManagement"
